# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0006_auto_20170209_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiltoparse',
            name='url',
            field=models.URLField(max_length=250, unique=True),
        ),
    ]
